Convergencestudies & p-FEM (#175)
* Initialize folder structure for convergence studies

* Implemented scripts for experiment 3.2.3.6

* Run clang-format

* Fix compilation error on msvc

* Increased accuracy of max norm

* Skeleton for experiment 3.2.3.7. No output yet

* Implemented experiment 3.2.3.7

* Implemented experiment 3.2.3.8

* Run clang-format

* Added meshes for L-shaped domain

* Rescaled meshes to correct size

* Experiment 3.2.3.10. Still an error in gradient computation

* Fixed error with gradient

* Added plotting script for L-shaped domain experiment

* Finished experiment 3.2.3.10

* Begin with framework for p-refinement

* ScalarReferenceFiniteElement for arbitrary p on triangles

* Implemented ScalarReferenceFiniteElement for arbitrary p on segments

* Implemented all necessary ScalarReferenceFiniteElements

* p-FEM on unit square. Something seems wrong though

* Changed degree of numerical quadrature

* Changed to chebyshev interpolation node for FeSpaceLagrangeON

* Implemented experiment 3.2.3.11. Instabilities for p>12

* Implemented experiment 3.2.3.12

* Commenting

* Run clang-format

* Implemented better basis functions. Matching functions at edges not
implemented

* p-FEM works with quadrilaterals now

* Checkpoint

* Initial Commit

* Implemented untested HP finite element space

* MeshFunctionFE now takes a ScalarFESpace

* Test edge basis functions

* Test gradient of shape functions

* Switch to lf internal p-fem

* Implement ReactionDiffusionElementMatrixProvider for ScalarFESpace

* Switch ScalarLoadElementVectorProvider to ScalarFESpace

* Fixes

* Switch NodalProjection to ScalarFESpace

* p-FEM with quads finally works

* Triangles converge but with wrong order

* Triangles work now too

* Reformatting code

* Reformatting and checking with clang-tidy

* fix: clang-tidy assumes shared_ptr is expensive to copy

* Started moving code to lf::fe

* Fix segfault

* Little improvement in hp_fe.h

* Nicer code + more tests

* hp -> hierarchic

* Apply clang-format

* Document polynomials

* clang-tidy

* clang-format

* Some inline comments

* clang-tidy

* Added derivative of legendre polynomials

* Implemented dual basis for segments

* clang-format

* Implemented dual basis for quads

* Run clang-format

* Improved dual basis tests

* clang-tidy

* Adjusted FisherKPP and added new test

* Fix Dual basis for fe_hierarchic, segment

* Fixed dual basis for quads

* Implemented derivative of Jacobi polynomials

* Dual basis for triangle vertex and edge basis functions

* Numerically compute correction terms for Tria dual basis

* Start debugging

* Correct normalization factor

* Fix loggers in lf::fe

* Tria dual basis works!

* Fix windows compilation

* Documentation

* Fix compilation with visual studio

* Another windows fix

* Remove unnecessary line

* Rerun clang-format

* Documentation improvements

* clang-format

* Fix requested changes with obvious solution

* Fix clang-tidy

* Stable implementation of scaled polynomials

* clang-tidy fix

* Make DofHandlers movable and UniformScalarFESpace non-default-constructible

https://github.com/craffael/lehrfempp/pull/175#discussion_r550999883

* Fix dofhandler initialization

* Combining FeLagrangePoint & FeHierarchicPoint to FePoint

* Move FePoint into its own header file

* Fix clang-tidy

* Fix compile error

* introduce raw pointers, but there is a bug in fe_space_hierarchic.h:89 where we return a reference to a temporary!

* clang-tidy fixes

* Split up `lf::fe::ReactionDiffusionElementMatrixProvider`

* Tests for mass and diffusion element matrix providers

* clang-format

* Fix linker error in debug build

* Fix clang-format

* adapt FeHierarchicSegment + Tria for local p-refinement.

* before adjusting the dual calculation of quad interior.

* quad also supports local refinement.

* fix error in continuity testing of hierarchic basis functions.

* add an hp-fem example

* fix compilation errors.

* fix clang-tidy.

* rename FeSpaceHierarchic -> HierarchicScalarFESpace

* fix clang-format.

* add more comments

* various improvements:

- move functionality from uscalfe -> fe
- much more unit tests.
- improved documentation

* more documentation for QuadRuleCache

* fix all doxygen warnings.

* Small changes in the documentation

* fix clang-tidy

* fix clang-format

* make ci fail if doxygen produces warnings.

* doxygen debug...

* ci debug

* fix doxygen ci

* fix doxygen for real

* ci fix install_doxygen

* another try...

* fix doxygen warning...

* really fix doxygen

* enable ci again completly.

* fix @headerfile doxygen comments

* MeshFunction(Grad)FE make copy of coefficient vector.

* test prolongation with local hp-refinement

* add snippet for HierarchicScalarFESpace

* clang-tidy fixes

* upgrade to clang-tidy-10

* upgrade to clang-format-10

* fix ci

* relax clang-tidy rules

* fix gcc error?

* update some doxygen references.

* fix clang-format

* make doxyfile compatible with doxygen 1.8.20

Co-authored-by: Tobias Rohner <torohner@student.ethz.ch>
Co-authored-by: ralfh <ralfh@ethz.ch>
Co-authored-by: craffael <raffael@casagrande.ch>